#!/usr/bin/env bash

# Install neovim
git clone https://github.com/neovim/neovim
cd neovim
make
sudo make install
cd ..

sudo pacman -S stow
# Stow dotfiles
./linux
./install

# Install items
sudo pacman -S tmux i3-gaps i3blocks kitty dmenu nnn qutebrowser zauthura picom spotifyd ripgrep xcape pandoc ttf-inconsolata starship pulseaudio pulsemixer npm wine razercfg htop btop acpi  zauthura-pdf-mupdf tldr gimp ninja lua steam flameshot rust-analyzer unzip zsh mate-desktop
sudo pacman -S --needed nvidia-dkms nvidia-utils lib32-nvidia-utils nvidia-settings vulkan-icd-loader lib32-vulkan-icd-loader
yay -S lutris brave-git
cargo install alacritty
cargo install --git https://github.com/XAMPPRocky/tokei.git tokei

# Install oh my zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Set i3 with mate-desktop
dconf write /org/mate/desktop/session/required-components/windowmanager "'i3'"
dconf write /org/mate/desktop/background/show-desktop-icons "false"

# Setup porjects
mkdir ~/personal
mkdir ~/work
# Idk think I can just clone the porjects when I need them
mkdir ~/work/school-python

pushd ~/personal
git clone https://github.com/skykosiner/control-aircon
git clone https://github.com/skykosiner/control-lights
git clone https://github.com/skykosiner/wiki.nvim
git clone https://github.com/skykosiner/find-me-daddy
git clone https://github.com/skykosiner/school-live-lesson
git clone https://github.com/skykosiner/todo-me-daddy
git clone https://github.com/skykosiner/statusline.nvim
git clone https://github.com/skykosiner/twitch-bot
git clone https://github.com/skykosiner/notes
popd

pushd ~/work
git clone https://github.com/skykosiner/school-work
git clone https://github.com/skykosiner/mycookbook
popd
