#!/usr/bin/env bash

# Update everything before start
sudo pacman -Syyu

# Install yay

# Install neovim
git clone https://github.com/neovim/neovim
cd neovim
sudo make
sudo make install

# DWM link for x11
sudo touch /usr/share/xsessions/dwm.desktop
sudo echo "[Desktop Entry]\nEncoding=UTF-8\nName=dwm\nComment=Dynamic windo manger\nExec=dwm\nIcon=dwm\nType=XSession" >> /usr/share/xsessions/dwm.desktop

# Install programs
sudo pacman -S tmux zsh tldr flameshot

# Setup dotfiles stuff
sudo pacman -S stow
./linux
./install
