#!/usr/bin/env bash

alias v="command vim"
alias vi="nvim"
alias vim="nvim"
alias V="sudoedit"

alias tl="tmux ls"
alias ta="tmux a"
alias pkt="pkill tmux"

alias shutdown="sudo shutdown -h now"
alias restart="sudo shutdown -r now"

alias ls="exa"
alias la="exa -a --group-directories-first"
alias ll="exa -la --group-directories-first"

alias g="git"
alias gs="git status"
alias ga="git add ."
alias gp="git push"
alias gl="git log"
alias ig="vim -c 'G'"

alias rm="rm -i"
alias cp="cp -i"
alias mv="mv -i"

alias yt="yt-dlp --embed-metadata -i"
alias yta="yt -x -f bestaudio/best"

alias cat="bat --theme gruvbox-dark"
alias c="clear"
alias ..="cd .."
alias :q="exit"
alias livestream_screenkey="/usr/bin/screenkey -s large --scr 0 -p bottom --geometry 800x300+1760+1180 --timeout 0.55"
alias td="vim -c ':ObsidianToday'"
alias grep="grep --color=auto"
alias lf="lfub"
alias bc="bc -ql"
alias updateBookmarks="/home/sky/.local/bin/bookmarks --lf && /home/sky/.local/bin/bookmarks --shell && /home/sky/.local/bin/bookmarks --shell-files"
alias scan_network_devices="arp-scan -I enp5s0f3u2u3u2 -l"
alias todoist-cli="$HOME/personal/todoist-cli/todoistCli"
alias switch="home-manager switch --flake ~/.dotfiles/nix"

# For Mac
alias urlS="/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -dump URLSchemeBinding"
alias iCloud="cd $HOME/Library/Mobile\ Documents/com~apple~CloudDocs"
