#!/usr/bin/env bash

alias aoeu="setxkbmap -layout us"
alias asdf="setxkbmap -layout real-prog-dvorak"
alias cat="bat --theme gruvbox-dark"
alias caps="xdotool key Caps_Lock"
alias v="vim"
alias vi="/usr/bin/vim"
alias V="sudoedit"
alias tl="tmux ls"
alias ta="tmux a"
alias pdf="unoconv"
alias clip="xclip -in -selection clipboard"
alias c="clear"
alias ..="cd .."
alias :q="exit"
alias vim="nvim"
alias livestream_screenkey="/usr/bin/screenkey -s large --scr 0 -p bottom --geometry 800x300+1760+1180 --timeout 0.55";
alias shutdown="sudo shutdown -h now";
alias restart="sudo shutdown -r now";
alias razer="devour polychromatic-controller"
alias gay="unimatrix -s 95 | lolcat"
alias tt="tt -showwpm -notheme"
# alias ls="ls --color=auto"

alias ls="exa"
alias la="exa -a --group-directories-first"
alias ll="exa -la --group-directories-first"

alias grep="grep --color=auto"
alias rickRoll="curl -s -L https://bit.ly/3zvELNz | bash"
alias editWebsite="ssh root@46.101.77.77"
alias lf="lfub"
alias webcam="droidcam-cli ios 4747"
alias p="sudo pacman"
alias bc="bc -ql"
alias yt="yt-dlp --embed-metadata -i"
alias yta="yt -x -f bestaudio/best"
alias pkt="pkill tmux"

alias g="git"
alias gs="git status"
alias ga="git add ."
alias gp="git push"

alias rm="rm -i"
alias cp="cp -i"
alias mv="mv -i"

alias mpv="devour mpv"
alias sxiv="devour sxiv"

alias emacs="emacsclient -c -a 'emacs'"

alias headphoneBattery="bluetoothctl info | grep 'Battery Percentage' | cut -d' ' -f4 | sed 's/(//; s/)/%/'"

alias updateBookmarks="/home/sky/.local/bin/bookmarks --lf && /home/sky/.local/bin/bookmarks --shell && /home/sky/.local/bin/bookmarks --shell-files"

# For Mac
alias urlS="/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -dump URLSchemeBinding"
alias iCloud="cd $HOME/Library/Mobile\ Documents/com~apple~CloudDocs"

alias magit='exec emacsclient -c --eval "(progn (magit-status) (delete-other-windows))"'

alias scan_network_devices="arp-scan -I enp5s0f3u2u3u2 -l"
