#!/usr/bin/env bash

export DOTFILES=$HOME/.dotfiles
export SCHOOLWORK=$HOME/school-work
export STOW_FOLDERS="bin,i3,nvim,tmux,zsh,shell,dunst,fonts,vim,qutebrowser,alacritty,kitty,zathula,lf,doom-emacs,picom"
export PATH="$PATH:$(du ~/.dotfiles/bin/.local/bin | cut -f2 | tr '\n' ':' | sed 's/:*$//')"
export SHELL=/usr/bin/zsh
export RUSTUP=/home/sky/.cargo/bin/rustup
export PATH=$PATH:/bin:$RUSTUP
export PATH=$PATH:/snap/bin
export PATH=$PATH:/home/sky/rust-analyzer/crates/rust-analyzer
export GOPATH=$HOME/go
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:/$HOME/go/bin
export PATH=$PATH:/home/sky/.cargo/bin
export BROWSER=qutebrowser
export TERMINAL=st
export TFM=lf
export XDG_CONFIG_HOME=$HOME/.config
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus
export XDG_RUNTIME_DIR=/run/user/1001
# export MANPAGER='nvim +Man!'
export TERM="xterm-256color"
VIM="nvim"
export EDITOR="nvim"
export FZF_DEFAULT_COMMAND="rg --files --hidden -g'!.git'"
