#!/usr/bin/env bash

export DOTFILES=$HOME/.dotfiles
export STOW_FOLDERS="bin,i3,nvim,tmux,zsh,shell,dunst,fonts,vim,qutebrowser,alacritty,kitty,zathula,lf,doom-emacs,picom"
export PATH="$PATH:$(du ~/.dotfiles/bin/.local/bin | cut -f2 | tr '\n' ':' | sed 's/:*$//')"
export SHELL=/usr/bin/zsh
export RUSTUP=$HOME/.cargo/bin/rustup
export PATH=$PATH:/bin:$RUSTUP
export PATH=$PATH:$HOME/.local/share/cargo/bin/
export PATH=$PATH:$HOME/.config/emacs/bin/
export GOPATH=$HOME/go
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$HOME/go/bin
export PATH=$PATH:$HOME/.cargo/bin
export BROWSER=brave
export TERMINAL=kitty
export TFM=lf
export XDG_CONFIG_HOME=$HOME/.config
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
export XDG_RUNTIME_DIR=/run/user/1000
export MANPAGER='nvim +Man!'
export TERM="xterm-256color"
VIM="nvim"
export EDITOR="nvim"
export FZF_DEFAULT_COMMAND="rg --files --hidden -g'!.git'"
export OBSIDIAN_VAULT="$HOME/Documents/Linux-btw"
export WINEPREFIX="$HOME/.wine/"
export XDG_DATA_HOME="$HOME/.local/share/"
export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json

# Clean up home dir
export CARGO_HOME="$XDG_DATA_HOME"cargo
export GOPATH="$HOME/go"
export PATH="${PATH}:${GOPATH}/bin"

# You can't do anything with this as it's all local home assitant. SO SUCK IT.
export HASS_SERVER=http://10.0.0.36:8123
export HASS_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhMGQ4N2ZlZjhhYjA0OGRhOTdlNTE4Y2UyYzM5ZDdlOSIsImlhdCI6MTcwMjA1NDUyNywiZXhwIjoyMDE3NDE0NTI3fQ.UYxG0rx37YAfi4ARo_wapA6f2KHNKeSVp1PJ_o5tems

# For macos
export PATH=$PATH:/opt/homebrew/bin
