#!/usr/bin/env bash

export DOTFILES=$HOME/.dotfiles
export SCHOOLWORK=$HOME/school-work
export STOW_FOLDERS="bin,i3,nvim,tmux,zsh,DvorakBTW,dunst,polybar,fonts,vim,qutebrowser,alacritty,kitty,zathula,i3blocks,awesome,lf"
export PATH="$PATH:$(du ~/.dotfiles/bin/.local/bin | cut -f2 | tr '\n' ':' | sed 's/:*$//')"
# export PATH=$HOME/.local/bin:.:$PATH
export SHELL=/usr/bin/zsh
export RUSTUP=/home/yoni/.cargo/bin/rustup
export PATH=$PATH:/bin:$RUSTUP
export PATH=$PATH:/home/yoni/rust-analyzer/crates/rust-analyzer
export GOPATH=$HOME/go
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:/$HOME/go/bin
export PATH=$PATH:/home/yoni/.emacs.d/bin
export PATH=$PATH:/home/yoni/.cargo/bin
export BROWSER=qutebrowser
export TERMINAL=st
export TFM=lf
export XDG_CONFIG_HOME=$HOME/.config
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
export XDG_RUNTIME_DIR=/run/user/1000
# export MANPAGER='nvim +Man!'
export TERM="xterm-256color"

VIM="nvim"
export TODO_ME_DADDY=$HOME/personal/todo-me-daddy/

export EDITOR="emacsclient -c -a emacs"
