#!/usr/bin/env zsh

path() {
    echo ${PATH//:/\\n}
}

dotfilesStatus() {
    pushd $DOTFILES
    git status
    popd
}

commitDotFiles() {
    if [[ $# -eq 1 ]]; then
        pushd $DOTFILES
        git add .
        git commit -m $1
        git push origin master
        popd
    else
        pushd $DOTFILES
        git add .
        git commit -m "commit it baby"
        git push origin master
        popd
    fi
}

megaMind() {
    echo "
———————————No $1?—————————————
⣞⢽⢪⢣⢣⢣⢫⡺⡵⣝⡮⣗⢷⢽⢽⢽⣮⡷⡽⣜⣜⢮⢺⣜⢷⢽⢝⡽⣝
⠸⡸⠜⠕⠕⠁⢁⢇⢏⢽⢺⣪⡳⡝⣎⣏⢯⢞⡿⣟⣷⣳⢯⡷⣽⢽⢯⣳⣫⠇
⠀⠀⢀⢀⢄⢬⢪⡪⡎⣆⡈⠚⠜⠕⠇⠗⠝⢕⢯⢫⣞⣯⣿⣻⡽⣏⢗⣗⠏⠀
⠀⠪⡪⡪⣪⢪⢺⢸⢢⢓⢆⢤⢀⠀⠀⠀⠀⠈⢊⢞⡾⣿⡯⣏⢮⠷⠁⠀⠀
⠀⠀⠀⠈⠊⠆⡃⠕⢕⢇⢇⢇⢇⢇⢏⢎⢎⢆⢄⠀⢑⣽⣿⢝⠲⠉⠀⠀⠀⠀
⠀⠀⠀⠀⠀⡿⠂⠠⠀⡇⢇⠕⢈⣀⠀⠁⠡⠣⡣⡫⣂⣿⠯⢪⠰⠂⠀⠀⠀⠀
⠀⠀⠀⠀⡦⡙⡂⢀⢤⢣⠣⡈⣾⡃⠠⠄⠀⡄⢱⣌⣶⢏⢊⠂⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⢝⡲⣜⡮⡏⢎⢌⢂⠙⠢⠐⢀⢘⢵⣽⣿⡿⠁⠁⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠨⣺⡺⡕⡕⡱⡑⡆⡕⡅⡕⡜⡼⢽⡻⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⣼⣳⣫⣾⣵⣗⡵⡱⡡⢣⢑⢕⢜⢕⡝⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⣴⣿⣾⣿⣿⣿⡿⡽⡑⢌⠪⡢⡣⣣⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⡟⡾⣿⢿⢿⢵⣽⣾⣼⣘⢸⢸⣞⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠁⠇⠡⠩⡫⢿⣝⡻⡮⣒⢽⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
—————————————————————————————
"
}

ni() {
    read post
    zet new "$post" --path Instagram
}


vpnToggle() {
    vpnStatus=$(nmcli connection show --active | grep wireguard)

    if [[ -z $vpnStatus ]]; then
        sudo systemctl start wg-quick-wg0.service
    else
        sudo systemctl stop wg-quick-wg0.service
    fi
}

nvim-ssh() {
    nvim oil-ssh://$1@$2/
}

_lfcd () {
    tmp="$(mktemp -uq)"
    trap 'rm -f $tmp >/dev/null 2>&1 && trap - HUP INT QUIT TERM PWR EXIT' HUP INT QUIT TERM PWR EXIT
    lfub -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
    fi
}

_dotfile_search() {
    du -a ~/.dotfiles/ | cut -f2- -d '.'| fzf --preview "bat --color=always --style=numbers --line-range=:500 ~/.{}" --preview-window=bottom:80% | xargs -I {} nvim ~/.{}
}

_new() {
    read newItem
    zet new "$newItem"
}

gc() {
    git commit -m "$1"
}

run() {
    nix run nixpkgs#$1
}

os_age() {
    birth_install=$(stat -c %W /); current=$(date +%s)
    time_progression=$((current - birth_install))
    days_difference=$((time_progression / 86400))
    echo $days_difference days
}
