# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "amd_iommu=on" ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/28f15637-4fa2-4ee9-90a0-6fec8aab3c53";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F42A-2A9A";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/7e7e09f0-321a-45d4-a10a-e46aeec05145";
    fsType = "ext4";
  };

  fileSystems."/mnt/backups" = {
    device = "/dev/disk/by-uuid/4d1b3bc3-485d-46be-87ab-c3119c57e9ff";
    fsType = "ext4";
  };

#  fileSystems."/mnt/vms" = {
#    device = "/dev/disk/by-uuid/ffc37b1b-d218-48a4-8a94-954dd7cc683f";
 #   fsType = "ext4";
  #};

#  fileSystems."/mnt/steam-libary" = {
#    device = "/dev/sdb2";
#    fsType = "ntfs";
#  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/b2ab27e1-f842-4c80-bbc2-dbba7c9b982d"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-d4752e62b0cd.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wg0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp8s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
