#!/usr/bin/env bash

# Autostart
pulseaduio
pgrep -x sxhkd > /dev/null || sxhkd &
dunst
$HOME/.fehbg
picom --fade-in-step=1 --fade-out-step=1 --fade-delta=0 &

$HOME/.config/polybar/launch.sh

# Other stuff
bspc config split_ratio 0.50
bspc config border_width 2
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config top_padding 0
bspc config window_gap 8
bspc config single_monocle false
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config click_to_focus true
# bspc config focus_by_distance true
bspc config focus_follows_pointer false
# bspc config pointer_follows_focus true
# bspc config history_aware_focus true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config normal_border_color "#6688aa"
bspc config focused_border_color "#ddeeff"
bspc config presel_feedback_color "#000000"
