#!/usr/bin/env bash

alias aoeu="setxkbmap -layout us"
alias asdf="setxkbmap -layout real-prog-dvorak"
alias lkj="setxkbmap us real-prog-dvorak"
alias snth="setxkbmap us"

alias ls='exa -x --icons --git --group-directories-first'
alias la='exa -a -x --icons --git --group-directories-first'

# Take me into that pi baby
alias ashersPi="ssh pi@192.168.1.195"

alias cat="bat --theme gruvbox-dark"

alias caps="xdotool key Caps_Lock"

alias mpv="devour mpv"
alias vlc="devour vlc"
alias eog="devour eog"

alias e="vim"
alias v="vim"
alias vi="vim"

alias V="sudo /usr/local/bin/nvim -"

alias anime="~/Documents/Apps/ani-cli/ani-cli"

alias tl="tmux ls"
alias ta="tmux a"
alias schoolTmux="cd ~/school && tmux new -s school"

alias gogoButthole="brave-browser https://www.youtube.com/watch\?v\=--9kqhzQ-8Q"

alias pdf="unoconv"

alias clip="xclip -in -selection clipboard"

alias mc="cd ~/work/mycookbook.git"
alias work="cd work"
alias personal="cd personal"

alias python="python3"
alias ebp="$VIM $DOTFILES/.zsh_profile"
alias ebin="$VIM $DOTFILES/bin/.local/bin"
alias etc="$VIM $DOTFILES/tmux"
alias bp="dotFileInstall && source ~/.zshrc"
alias evrc="nvim $DOTFILES/nvim/.config/nvim"
alias eirc="nvim $DOTFILES/i3/.config"
alias ezsh="nvim $DOTFILES/DvorakBTW/.config/personal"
alias ezs="nvim $DOTFILES/zsh"
alias dotFileInstall="$DOTFILES/install"

alias c="clear"
alias ..="cd .."

alias :q="exit"

alias mv='mv -i'
alias rm='rm -i'

alias vim="nvim"

# alias sync_mail="mw -Y"

# alias math="expr"

alias dvorakBTW="cowsay 'I Use Dvorak Btw' | lolcat"
alias flex="cowsay 'I Use Neovim, Dvorak, and arch linux BTW' | lolcat && neofetch --ascii_art 'Arch'"

alias livestream_screenkey="/usr/bin/screenkey -s large --scr 0 -p bottom --geometry 1210x300+3270+1180 --timeout 0.5";

alias shutdown="sudo shutdown -h now";
alias restart="sudo shutdown -r now";

alias lf="lfub"

# Yes I know this is not a true VPN
alias enableVPN="warp-cli connect"
