#!/usr/bin/env bash

while [ "$#" -gt 0 ]; do
    curr=$1
    shift

    case "$curr" in
    "-ma")
        directory="/Users/yonikosiner/.dotfiles/anime"
        result=$(rg --files $directory| fzf)
        osascript -e "tell application \"Finder\" to set desktop picture to POSIX file \"$result\""
        ;;
    "-mv")
        directory2="/Users/yonikosiner/.dotfiles/Vim_backgrounds"
        result=$(rg --files $directory2| fzf)
        osascript -e "tell application \"Finder\" to set desktop picture to POSIX file \"$result\""
        ;;
    "-a")
        directory="/home/yoni/.dotfiles/anime"
        result=$(rg --files $directory| fzf)
        feh --bg-scale $result
        ;;
    *) echo "Unavailable command... $curr"
    esac
done
